# Generated by Django 2.2.9 on 2019-12-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='Job',
        ),
    ]
